// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvmvfkrrrtabdkzgccoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2bXZma3JycnRhYmRremdjY29hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NzgzNjMsImV4cCI6MjA3MDU1NDM2M30.wscajzaR_RKsDLfDINt-nPFDNguUDT9XoDVuf2hOT_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});